### ISSUE TITLE
Is lean-stack dead?

### ISSUE THREAD

**Issue by anlexN** [wayofthefuture/lean-stack#1]

**Comment by wayofthefuture** [comment]
Nope... PR's welcome!

**Comment by anlexN** [comment]
But you have no any updates for 2 years. why?

**Comment by wayofthefuture** [comment]
1 year

**Comment by wayofthefuture** [comment]
i put in the work... time for someone else to contribute

**Comment by anlexN** [comment]
Can you train me? i am willing to be your contributor

**Comment by wayofthefuture** [comment]
lean-stack is not widely used, more of just a fun side project. your best bet is to go mainstream with the masses... webpack + reactjs + nodejs + mongodb

**Comment by anlexN** [comment]
anything else? please give some more suggestions!

**Comment by wayofthefuture** [comment]
nope that should be good!
